### ISSUE TITLE
Link  to Contributing Guide is broken

### ISSUE THREAD

**Issue by munezerobagira** [GeoBrodas/linksnap#6]
Current link to Contributing Guide shows 404  
https://github.com/GeoBrodas/linksnap/blob/main

**Comment by GeoBrodas** [comment]
> Current link to Contributing Guide shows 404  
> https://github.com/GeoBrodas/linksnap/blob/main

Yess I'll set it up if you're interested🙂! I haven't made on yet.

**Comment by munezerobagira** [comment]
I am interested

**Comment by GeoBrodas** [comment]
Cool give me a day's time, I'll even set up some linting workflow 🙌🏼

**Comment by GeoBrodas** [comment]
Welcome to Linksnap, looking forward to your contributions, I'll set up a Kanban project as well to list the issues on the application.
